<?php

namespace Database\Seeders\SmappData;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder généré automatiquement depuis le dump smapp.sql
 * Table: users
 * Lignes: 43
 */
class UsersSeeder extends Seeder
{
    public function run(): void
    {
        $table = 'users';

        $rows = [
            ['id' => 1, 'school_id' => 1, 'niveau_id' => null, 'name' => 'Super Admin', 'email' => 'admin@elites-school.test', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 0, 'email_verified_at' => null, 'password' => '$2y$12$jGrmkx73OSew7nBUaSNvveFcWKv2ApcHphA54c0KGrG/pHDrdCK8m', 'remember_token' => null, 'created_at' => '2026-08-10 19:27:54', 'updated_at' => '2026-08-17 07:58:54'],
            ['id' => 2, 'school_id' => 2, 'niveau_id' => null, 'name' => 'Direction Maternelle', 'email' => 'maternelle@elites-school.test', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 0, 'email_verified_at' => null, 'password' => '$2y$12$8kM/4XReDMYJ7CBCXYRbdeoWAwHtkITRksqDQehAxEV.RwmMHPNiS', 'remember_token' => null, 'created_at' => '2026-08-10 19:27:55', 'updated_at' => '2026-08-17 01:33:09'],
            ['id' => 3, 'school_id' => 3, 'niveau_id' => null, 'name' => 'Direction Primaire', 'email' => 'primaire@elites-school.test', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 0, 'email_verified_at' => null, 'password' => '$2y$12$ODcmM6AXwwub9wa.uNA2OO8dAqYk7ps4923PoixYzkkX.zCr4cF96', 'remember_token' => null, 'created_at' => '2026-08-10 19:27:55', 'updated_at' => '2026-08-11 06:11:57'],
            ['id' => 4, 'school_id' => 1, 'niveau_id' => null, 'name' => 'TCHIOFFOUO Josué', 'email' => 'directeur@elites-school.test', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 0, 'email_verified_at' => null, 'password' => '$2y$12$9M6HcZuw0zhFLfbw7RTKHusobnK8qsNilJaZvH0s0Qc4epSZHdZU6', 'remember_token' => null, 'created_at' => '2026-08-10 19:27:56', 'updated_at' => '2026-08-11 06:11:58'],
            ['id' => 5, 'school_id' => 1, 'niveau_id' => null, 'name' => 'NGUEMA Alice', 'email' => 'censeur@elites-school.test', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 0, 'email_verified_at' => null, 'password' => '$2y$12$VqT1WP5V/7es.QW4p0h0fe5yf0kqfLcn.9fuEp0pjo2MUBHae7rO2', 'remember_token' => null, 'created_at' => '2026-08-10 19:27:56', 'updated_at' => '2026-08-11 06:11:58'],
            ['id' => 6, 'school_id' => 3, 'niveau_id' => null, 'name' => 'Solange ATEBA', 'email' => 'titulaire.primaire@elites-school.test', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 0, 'email_verified_at' => null, 'password' => '$2y$12$Z4/I3VumxOggVbMQVDmCr.N3Ku2KdtGoIjLLZIUkIdUIMZB3JN11G', 'remember_token' => null, 'created_at' => '2026-08-10 19:28:48', 'updated_at' => '2026-08-10 19:28:48'],
            ['id' => 7, 'school_id' => 2, 'niveau_id' => null, 'name' => 'Solange ATEBA', 'email' => 'titulaire.maternelle@elites-school.test', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 0, 'email_verified_at' => null, 'password' => '$2y$12$H6M0.CUpVJn3KOEkiEthMOoDTuHiVn3L/.fe6zcwRkS9hhdvXXxUu', 'remember_token' => null, 'created_at' => '2026-08-10 19:29:06', 'updated_at' => '2026-08-10 19:29:06'],
            ['id' => 8, 'school_id' => 1, 'niveau_id' => null, 'name' => 'USENI Venyteh', 'email' => 'principal@elites-school.test', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 0, 'email_verified_at' => null, 'password' => '$2y$12$teFEEonrvYcW8Xw.gnEH8OI/MoudzKoEJclicpwdv78ZqkDDM58Nq', 'remember_token' => null, 'created_at' => '2026-08-11 06:11:58', 'updated_at' => '2026-08-11 06:11:58'],
            ['id' => 9, 'school_id' => 1, 'niveau_id' => null, 'name' => 'AKONO EVANG Nathan', 'email' => 'surveillant@elites-school.test', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 0, 'email_verified_at' => null, 'password' => '$2y$12$UlnlmkJTd.K3mRWr8XDh2.U3r6jKMuEFHd98n0rvKfwT5jPOHfnRy', 'remember_token' => null, 'created_at' => '2026-08-11 06:11:59', 'updated_at' => '2026-08-11 06:11:59'],
            ['id' => 17, 'school_id' => 2, 'niveau_id' => null, 'name' => 'TAFON MIRADINE SHIEN', 'email' => 'tafon.miradine.shien@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$wvW41Q6xGK79gOOWLOHUIONJASnFZHUuqFEDYKoylOp2OPCV5hIqe', 'remember_token' => null, 'created_at' => '2026-08-16 09:08:06', 'updated_at' => '2026-08-16 09:08:06'],
            ['id' => 18, 'school_id' => 2, 'niveau_id' => null, 'name' => 'GLAINNES FOMONYUY', 'email' => 'glainnes.fomonyuy@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$d26pD18DjBw8kJHl6F4ZA.2T.5OSffCIP.28O1crQVu7eLTkpWNP2', 'remember_token' => null, 'created_at' => '2026-08-16 09:08:06', 'updated_at' => '2026-08-16 09:08:06'],
            ['id' => 19, 'school_id' => 2, 'niveau_id' => null, 'name' => 'AGBORNDE CATHERINE BESONG', 'email' => 'agbornde.catherine.besong@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$L3jIBM6znRZ6GGq5Eya1DOTKcdap9SRuU.QfUM3g2zYQpf/Cb3npe', 'remember_token' => null, 'created_at' => '2026-08-16 09:08:06', 'updated_at' => '2026-08-16 09:08:06'],
            ['id' => 20, 'school_id' => 2, 'niveau_id' => null, 'name' => 'FABIOLA ABURINYUY NSAIDZEDZE', 'email' => 'fabiola.aburinyuy.nsaidzedze@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$.U8N7BN3QJgBrtkEbzSgn.7qwIG5UCvFJU0qauwDsoNdPoxWsyQjC', 'remember_token' => null, 'created_at' => '2026-08-16 09:08:06', 'updated_at' => '2026-08-16 09:08:06'],
            ['id' => 21, 'school_id' => 2, 'niveau_id' => null, 'name' => 'CHEMO LAURIETTA BUVA', 'email' => 'chemo.laurietta.buva@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$Fk25rRaghetRSTmHySU7Nuywk6q3B1OSdoFq/a2zf/ISg6FnoBLxC', 'remember_token' => null, 'created_at' => '2026-08-16 09:08:07', 'updated_at' => '2026-08-16 09:08:07'],
            ['id' => 22, 'school_id' => 2, 'niveau_id' => null, 'name' => 'TENDONGZE NKEONGAFACK CHARYL MANYINGOCH', 'email' => 'tendongze.nkeongafack.charyl.manyingoch@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 0, 'email_verified_at' => null, 'password' => '$2y$12$fBg0Jk06g3oeLXQIHLdGVubih8.QaIg58sYqHEEde4/fsxLdWB/N2', 'remember_token' => null, 'created_at' => '2026-08-16 09:08:07', 'updated_at' => '2026-08-16 19:00:20'],
            ['id' => 23, 'school_id' => 2, 'niveau_id' => null, 'name' => 'MOUNA GOUYOUK épse TOUNOUMOU', 'email' => 'mouna.gouyouk.epse.tounoumou@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$04nRqali2RXbDtEY2zKLjeqdGgI5DSA51RwZmSqocUVJ62MqVXi3y', 'remember_token' => null, 'created_at' => '2026-08-16 09:08:07', 'updated_at' => '2026-08-16 09:08:07'],
            ['id' => 24, 'school_id' => 2, 'niveau_id' => null, 'name' => 'ATEBA ELOUANGUE AMANDINE', 'email' => 'ateba.elouangue.amandine@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$YELNWGNdzajH9uWf2H.07eWA/XQmsxu2piDAPP/tBgvLiZy599wzi', 'remember_token' => null, 'created_at' => '2026-08-16 09:08:07', 'updated_at' => '2026-08-16 09:08:07'],
            ['id' => 25, 'school_id' => 2, 'niveau_id' => null, 'name' => 'TANKE NDONGO SALOME HORTENSE', 'email' => 'tanke.ndongo.salome.hortense@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$TVUD79GUUtP5evzO.WJ/zOGn9QOIWJfpp7o2dWkLI1oGAOwt9pyYW', 'remember_token' => null, 'created_at' => '2026-08-16 09:08:08', 'updated_at' => '2026-08-16 09:08:08'],
            ['id' => 26, 'school_id' => 2, 'niveau_id' => null, 'name' => 'NANGA TSIGUE EMELINE VARTAN', 'email' => 'nanga.tsigue.emeline.vartan@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$u0JVYUxcYvGcwqig9VoSDOeL8QZSjap.5DzQk9J7IKFAq5s1p76RO', 'remember_token' => null, 'created_at' => '2026-08-16 09:08:08', 'updated_at' => '2026-08-16 09:08:08'],
            ['id' => 91, 'school_id' => 3, 'niveau_id' => null, 'name' => 'NCHANJI ELEXINE BONGABI', 'email' => 'nchanji.elexine.bongabi@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$Vg2g5BMz9Cq5meZaUaJAUuAphIdSKQVKziV6Wx.bfPsFF1JCG6LSW', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:44', 'updated_at' => '2026-08-16 09:38:44'],
            ['id' => 92, 'school_id' => 3, 'niveau_id' => null, 'name' => 'SHU FUHNWI KELLY', 'email' => 'shu.fuhnwi.kelly@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$qy4Hs7wjlVLrU8rFVHUGBO8pI0hOE6EOI8E0wynwYsV7wR8MaWCwG', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:44', 'updated_at' => '2026-08-16 09:38:44'],
            ['id' => 93, 'school_id' => 3, 'niveau_id' => null, 'name' => 'NGOMBA MANDE GERTRUDE', 'email' => 'ngomba.mande.gertrude@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$T9eVX5Jtx138.sMLQAO2EOG6IYaFIWnaBMJRFXcvObMdGFfeo4H4q', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:44', 'updated_at' => '2026-08-16 09:38:44'],
            ['id' => 94, 'school_id' => 3, 'niveau_id' => null, 'name' => 'NGEE LINUS', 'email' => 'ngee.linus@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$A8GSbQh11n0MbOU/d9l/Nu3FIW1aLl6wcEZ4yUFhj1OZGGoQjOB2K', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:44', 'updated_at' => '2026-08-16 09:38:44'],
            ['id' => 95, 'school_id' => 3, 'niveau_id' => null, 'name' => 'PASCALINE MBONGEH', 'email' => 'pascaline.mbongeh@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$Da/CUVt26EeQ5./aiF3aJeoD/EIH6wIGn1Dgvf/YfMrirkmHmYVJm', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:45', 'updated_at' => '2026-08-16 09:38:45'],
            ['id' => 96, 'school_id' => 3, 'niveau_id' => null, 'name' => 'JOEL NGALA NGWA', 'email' => 'joel.ngala.ngwa@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$fZR5pMe4posQue6uk37m8O00PCwWusDWJJdkA948jwArzFBMp7UDC', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:45', 'updated_at' => '2026-08-16 09:38:45'],
            ['id' => 97, 'school_id' => 3, 'niveau_id' => null, 'name' => 'MANGEH SANDRINE', 'email' => 'mangeh.sandrine@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$H9nKdQc.lSJzMqV8q.WauuRQwHyyYofh9mcsPWXKbKvu7fdzrCTsO', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:45', 'updated_at' => '2026-08-16 09:38:45'],
            ['id' => 98, 'school_id' => 3, 'niveau_id' => null, 'name' => 'TENDONGMOH DELPHINE', 'email' => 'tendongmoh.delphine@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$oToDnNB60FXinOoxkXab8.0T0jsmV2G5JkyYteXX9kX9DXReA4qHu', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:45', 'updated_at' => '2026-08-16 09:38:45'],
            ['id' => 99, 'school_id' => 3, 'niveau_id' => null, 'name' => 'AZONGOKOH SUZAN EGOFU', 'email' => 'azongokoh.suzan.egofu@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$j4QrteIpNkfj4zyXPuomC.hSTvjB1hZkafHF/Nl2Rcyae2FE.sJoG', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:46', 'updated_at' => '2026-08-16 09:38:46'],
            ['id' => 100, 'school_id' => 3, 'niveau_id' => null, 'name' => 'TFUMGAH TUME EDITH', 'email' => 'tfumgah.tume.edith@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$ACgeFoBoH7t89mV7ruQO5uUYd3PPzRpuevR9FiQCsdQvsD7hY3oZG', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:46', 'updated_at' => '2026-08-16 09:38:46'],
            ['id' => 101, 'school_id' => 3, 'niveau_id' => null, 'name' => 'NGWA PAUL NSOH', 'email' => 'ngwa.paul.nsoh@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$f9XKJISIJdE7ZtBTgkDF9u7uxn2hcdD7Teh4HpuaCdurpV77KIU6C', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:46', 'updated_at' => '2026-08-16 09:38:46'],
            ['id' => 102, 'school_id' => 3, 'niveau_id' => null, 'name' => 'FRU DIDIER ACHIRI', 'email' => 'fru.didier.achiri@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$VRybdEcIXJj4ioxHo/tCs.0QtiWhc8q/MpJsFyYGEn79Wd69J2RMC', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:46', 'updated_at' => '2026-08-16 09:38:46'],
            ['id' => 103, 'school_id' => 3, 'niveau_id' => null, 'name' => 'BOIGA DJANABOU', 'email' => 'boiga.djanabou@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$Y1Y81cDtXKIydC5TI49MiOgtJhJhl34pRmOI8rFibQXRvPNwenUku', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:47', 'updated_at' => '2026-08-16 09:38:47'],
            ['id' => 104, 'school_id' => 3, 'niveau_id' => null, 'name' => 'AGOIUD NANGA LETICIA', 'email' => 'agoiud.nanga.leticia@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$3ADw8hSBydESOVOebVHjhOOwJtXnqIe0Vbmqfppj8UATvjbD09WWS', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:47', 'updated_at' => '2026-08-16 09:38:47'],
            ['id' => 105, 'school_id' => 3, 'niveau_id' => null, 'name' => 'MELIGUI ORAL ROBERT', 'email' => 'meligui.oral.robert@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$m4DL6ogCCOh3xmKXd476buerlz0pBlvMp.hSpwKfoAXYGimTeWu6O', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:47', 'updated_at' => '2026-08-16 09:38:47'],
            ['id' => 106, 'school_id' => 3, 'niveau_id' => null, 'name' => 'KESSE DORIS', 'email' => 'kesse.doris@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$o3Vy1LJeJ.7TKkML7vwNPeC.8X.erSPMgTQl1OL7OypLa4z.fCMC2', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:47', 'updated_at' => '2026-08-16 09:38:47'],
            ['id' => 107, 'school_id' => 3, 'niveau_id' => null, 'name' => 'LOAKE LOAKE SYLVERE DARIOT', 'email' => 'loake.loake.sylvere.dariot@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$zg2G6KM29TqjW6mtW6M3R.hcszWHnuk7bVgJ8wFxpyVvjcNKYXygW', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:48', 'updated_at' => '2026-08-16 09:38:48'],
            ['id' => 108, 'school_id' => 3, 'niveau_id' => null, 'name' => 'NDZAKOMO LYDIE épse BENGONO', 'email' => 'ndzakomo.lydie.epse.bengono@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$mVsTL6UOEOfuhgZdg7vFPO7gHtZnVsGC/.VodwexzXS3s2fLF9/OO', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:48', 'updated_at' => '2026-08-16 09:38:48'],
            ['id' => 109, 'school_id' => 3, 'niveau_id' => null, 'name' => 'MUMENG PRUDENCIA NDZI', 'email' => 'mumeng.prudencia.ndzi@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$bWGCu.NoAHws8.wd/.KdSuE1m82LU0wYDn0d67Ci24UkOvK68vBkG', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:48', 'updated_at' => '2026-08-16 09:38:48'],
            ['id' => 110, 'school_id' => 3, 'niveau_id' => null, 'name' => 'SAIDOU HAMAN', 'email' => 'saidou.haman@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$sv4d2gsIEFUyGw7giig1NelVzvNq7i8J6jA9VEmcgcWlqOGAfGhRG', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:48', 'updated_at' => '2026-08-16 09:38:48'],
            ['id' => 111, 'school_id' => 3, 'niveau_id' => null, 'name' => 'DJATOTE PAULINE CLARISSE', 'email' => 'djatote.pauline.clarisse@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$fioMGE0rh94A6iqwfc2oj.7fvPEW275fCpFkzts/Zv7.PgejzOj3W', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:49', 'updated_at' => '2026-08-16 09:38:49'],
            ['id' => 112, 'school_id' => 3, 'niveau_id' => null, 'name' => 'WAFFO OLGA FLORE', 'email' => 'waffo.olga.flore@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$33rEwaIhlEoQoYh16zY0gO07Ycwl6ojZQZW6.bDQp8amJn.4Za8U6', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:49', 'updated_at' => '2026-08-16 09:38:49'],
            ['id' => 113, 'school_id' => 3, 'niveau_id' => null, 'name' => 'YAKA ELOBE MICHAEL', 'email' => 'yaka.elobe.michael@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$m4jwOnAy/z1vJ2Z4Xusvw.3SEpkj2KhuIBPRPEj/h06A9NabTowh.', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:49', 'updated_at' => '2026-08-16 09:38:49'],
            ['id' => 114, 'school_id' => 3, 'niveau_id' => null, 'name' => 'MPOLENGUE WYSTRIDE', 'email' => 'mpolengue.wystride@elite.school', 'phone' => null, 'locale' => 'fr', 'is_active' => 1, 'doit_changer_mot_de_passe' => 1, 'email_verified_at' => null, 'password' => '$2y$12$lbcjzKq.LUvnvOJyxOzBXeSzE9DTGNp.o3PPIh5PP5mDpsFcR9Yky', 'remember_token' => null, 'created_at' => '2026-08-16 09:38:49', 'updated_at' => '2026-08-16 09:38:49'],
        ];
        DB::table($table)->insert($rows);

    }
}
